
package de.Steamon;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DefaultSteamonServiceService", targetNamespace = "http://service.steamon.de/", wsdlLocation = "http://im-lamport:8080/steamon-0.1/DefaultSteamonService?WSDL")
public class DefaultSteamonServiceService
    extends Service
{

    private final static URL DEFAULTSTEAMONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEFAULTSTEAMONSERVICESERVICE_EXCEPTION;
    private final static QName DEFAULTSTEAMONSERVICESERVICE_QNAME = new QName("http://service.steamon.de/", "DefaultSteamonServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://im-lamport:8080/steamon-0.1/DefaultSteamonService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEFAULTSTEAMONSERVICESERVICE_WSDL_LOCATION = url;
        DEFAULTSTEAMONSERVICESERVICE_EXCEPTION = e;
    }

    public DefaultSteamonServiceService() {
        super(__getWsdlLocation(), DEFAULTSTEAMONSERVICESERVICE_QNAME);
    }

    public DefaultSteamonServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEFAULTSTEAMONSERVICESERVICE_QNAME, features);
    }

    public DefaultSteamonServiceService(URL wsdlLocation) {
        super(wsdlLocation, DEFAULTSTEAMONSERVICESERVICE_QNAME);
    }

    public DefaultSteamonServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEFAULTSTEAMONSERVICESERVICE_QNAME, features);
    }

    public DefaultSteamonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DefaultSteamonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DefaultSteamonService
     */
    @WebEndpoint(name = "DefaultSteamonServicePort")
    public DefaultSteamonService getDefaultSteamonServicePort() {
        return super.getPort(new QName("http://service.steamon.de/", "DefaultSteamonServicePort"), DefaultSteamonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DefaultSteamonService
     */
    @WebEndpoint(name = "DefaultSteamonServicePort")
    public DefaultSteamonService getDefaultSteamonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.steamon.de/", "DefaultSteamonServicePort"), DefaultSteamonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEFAULTSTEAMONSERVICESERVICE_EXCEPTION!= null) {
            throw DEFAULTSTEAMONSERVICESERVICE_EXCEPTION;
        }
        return DEFAULTSTEAMONSERVICESERVICE_WSDL_LOCATION;
    }

}
