
package de.Steamon;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DefaultSteamonService", targetNamespace = "http://service.steamon.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DefaultSteamonService {


    /**
     * 
     * @return
     *     returns java.util.List<de.Steamon.Software>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSoftwareChoicesForFloBank", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.GetSoftwareChoicesForFloBank")
    @ResponseWrapper(localName = "getSoftwareChoicesForFloBankResponse", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.GetSoftwareChoicesForFloBankResponse")
    public List<Software> getSoftwareChoicesForFloBank();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns de.Steamon.AccountItem
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activateKey", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.ActivateKey")
    @ResponseWrapper(localName = "activateKeyResponse", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.ActivateKeyResponse")
    public AccountItem activateKey(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        SoftwareKey arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns de.Steamon.Account
     * @throws AccountException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.CreateAccountResponse")
    public Account createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        Account arg0)
        throws AccountException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns de.Steamon.SoftwareKey
     * @throws AccountException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyKey", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.BuyKey")
    @ResponseWrapper(localName = "buyKeyResponse", targetNamespace = "http://service.steamon.de/", className = "de.Steamon.BuyKeyResponse")
    public SoftwareKey buyKey(
        @WebParam(name = "arg0", targetNamespace = "")
        Software arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Account arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        TransactionDTO arg2)
        throws AccountException_Exception
    ;

}
